<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>umContentCreator</PackageId>
    <Product>umContentCreator</Product>
    <Title>umContentCreator</Title>
    <Version>15.0.0</Version>
    <Authors>OSKI solutions</Authors>
    <PackageProjectUrl>https://oski.site/</PackageProjectUrl>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Kirill19837/umContentCreator</RepositoryUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>Enhance your Umbraco CMS with AI-driven content generation.
This package integrates both Chat GPT and Stability APIs, providing a seamless UI for creating, managing, and customizing AI-generated text and images for your text and media properties. Gain more control over content with options for max words, model behavior, and easy content appending or replacement. In addition to image generation based on your input, the package also allows you to easily insert images from Google Search, giving you even more flexibility and creative power.</Description>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageTags>umbraco-marketplace</PackageTags>
    <PackageReleaseNotes>1)Added support for Umbraco 15
2)Added support for the Stability API for image generation
3)Added the ability to add images from Google
4)Updated the design of modal windows</PackageReleaseNotes>
  </PropertyGroup>
  
  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\umContentCreator.Core\umContentCreator.Core.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="MyPackages\" />
    <Folder Include="wwwroot\App_Plugins\" />
  </ItemGroup>
  
</Project>
